#pragma once

#include "NativeGameplayTags.h"

namespace XwItemTags
{
    XWITEMSYSTEMRUNTIME_API    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Equipment);
    XWITEMSYSTEMRUNTIME_API    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Stuff);
    XWITEMSYSTEMRUNTIME_API    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumables);
    XWITEMSYSTEMRUNTIME_API    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Task);
}